#!/bin/sh

cat <<EOF > /etc/init/control-alt-delete.conf
# control-alt-delete - emergency keypress handling
#
# This task is run whenever the Control-Alt-Delete key combination is
# pressed.  Usually used to shut down the machine.
#
# Do not edit this file directly. If you want to change the behaviour,
# please create a file control-alt-delete.override and put your changes there.

#start on control-alt-delete
exec /usr/bin/logger -p security.info "Control-Alt-Delete pressed"
EOF

cat <<EOF > /etc/init/control-alt-delete.override
exec /usr/bin/logger -p security.info "Control-Alt-Delete pressed"
EOF
